### ISSUE TITLE
[moved] Debug errors with append, group, etc.

### ISSUE THREAD

**Issue by alvinwan** [dsten/datascience#1]
- [x] `append` doesn't work
- [x] `zip` should be used to construct columns in `from_rows`
- [x] `group` by a zipped column should do the right thing, but currently expands the contents of tuples
- [x] `group` should not introduce a new column if a column is passed in

**Comment by papajohn** [comment]
Is there a broken test for the last item? Now all existing tests pass.

**Comment by alvinwan** [comment]
Oop, I never finished it. `test_data.py` line 328 has the incomplete test; I'll amend it right now.

**Comment by alvinwan** [comment]
Actually, I think it should be valid.... is it?

**Comment by papajohn** [comment]
Looks good to me.
