### ISSUE TITLE
append_column method doesn't exist

### ISSUE THREAD

**Issue by henryem** [dsten/datascience#113]
The documentation for Tables lists a method called append_column, but there doesn't seem to be such a method.

**Comment by SamLau95** [comment]
It looks like this is cause the package isn't updated to the latest version on our servers.
![screenshot 2015-10-07 23 06 48](https://cloud.githubusercontent.com/assets/2468904/10358919/1efd8cec-6d48-11e5-83a5-6c11c0dd59e8.png)

The latest `__setitem__` method actually uses `Table.append_column` (https://github.com/dsten/datascience/blob/master/datascience/tables.py#L156)

@ryanlovett , can you update us to the latest version? It should be `0.3.dev15`.

**Comment by SamLau95** [comment]
This method is now available on the servers!
