### ISSUE TITLE
There should be some way to relabel without getting an exception when a column doesn't exist

### ISSUE THREAD

**Issue by henryem** [dsten/datascience#114]
In iPython notebooks, rerunning a cell with relabel() causes an exception.  That's confusing to students, who don't typically have a good mental model of notebook kernel state.  It would be nice if relabel() were idempotent, or if there were an idempotent version.

**Comment by SamLau95** [comment]
Agreed. Students have trouble with table mutation in general.

However, this would break existing code that depended on `Table.relabel` to mutate the table. Any ideas on the best course of action here? Maybe this is something we'll have to table for next semester.

**Comment by deculler** [comment]
It could just be silent if the source label does not exist and the target
label does.  Nothing would break an re-eval would be fine.

It is amazing how far they get without mutation...

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by SamLau95** [comment]
That case would also come up if a student tries to rename a column to an existing column, in which case I think throwing an error is more appropriate since silently failing will be confusing (students expects a column to have values but it doesn't).

**Comment by henryem** [comment]
Can we just have a relabeled() (or perhaps with_relabeling() if that looks too close to relabel()) method that is a pure function?  I think it's fine for such a method to throw an exception, since you're probably making a mistake if you call it on a table without the source column.  Then relabel() can be deprecated, or we can at least not teach it in the class next semester.

Btw, along the same vein, it would be nice to have a pure-function with_column() method that adds a column to a table.  Then I think we could have avoided mutation entirely.

**Comment by SamLau95** [comment]
Yeah, I like that idea.
