### ISSUE TITLE
Generalize pivot_hist to bar charts and plots

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#13]

**Comment by SamLau95** [comment]
@papajohn Doing some spring cleaning on our issues. Is this still something we want to do?

**Comment by deculler** [comment]
I wrote a new pivot_bin that is much more general and mirrors bin. With the
new hist or with bar you can visualize the result.  There are some demos
under text that show this in action.  So I think pivot_hist should be
removed.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley
