### ISSUE TITLE
Table.take documentation missing

### ISSUE THREAD

**Issue by SamLau95** [dsten/datascience#134]
After merging #120 the documentation for `Table.take` is now gone on data8.org: http://data8.org/datascience/_autosummary/datascience.tables.Table.take.html#datascience.tables.Table.take and http://data8.org/datascience/tables.html (although running `Table.take?` in IPython works fine).

@stefanv , could you look into this?

**Comment by stefanv** [comment]
On it.

**Comment by stefanv** [comment]
That should do it.
