### ISSUE TITLE
Add simple syntax for drawing normal curves and shading CDFs as areas

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#136]

**Comment by deculler** [comment]
I agree with this.  It wasn't entirely clear to me that you couldn't do
what we saw today with the kwargs and plot, but I imagine that you get
close but not all the way there.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by SamLau95** [comment]
@ericz82 Wanna take this one? :) Essentially, we'd like to do the stuff in https://youtu.be/atzB2sWA3pU?t=20m39s in an easy way.

**Comment by papajohn** [comment]
That's exactly what we want — Ani requested a one-liner to draw the same
diagrams that she designed in that last lecture.

**Comment by ericz82** [comment]
A few clarifying questions:

1. Is this method going to be a part of the Table class? If it is, in what way will it be using data from Table instances?
2. Right now I think the only argument for the function is the z-score which results in the area of the CDF being plotted on a standard normal curve with mean=0, variance=1. Do we want mean and variance to also be available as arguments? With respective default values as 0 and 1?
3. Final clarification: the purpose of the function is to generate a plot displaying normal curve with the area underneath to the left of the z-score shaded?

**Comment by a-adhikari** [comment]
2. Yes, please.
3. To generate a normal curve with the area between two values of z shaded. Default left end -infinity, default right end infinity.
Thanks!
Ani

**Comment by papajohn** [comment]
1. There's no data set involved — just a function to generate a curve
shaded by two endpoints.

-John

**Comment by ericz82** [comment]
Hmmmm... which file should I place this function in? util.py?

**Comment by papajohn** [comment]
Yes, that sounds right.
