### ISSUE TITLE
Allow plots settings on individual histograms when using hist()

### ISSUE THREAD

**Issue by SamLau95** [dsten/datascience#140]
For tables with multiple columns, calling `hist()` produces multiple histograms. However, calling `plots.xlabel(...)` after calling `hist()` only changes the label of the final histogram. It would be convenient to be able to specify labels for each of the individual histograms.

Not a high priority though!

**Comment by papajohn** [comment]
I don't see a good interface for this. I think the right answer is to generate each histogram individually and style it before drawing the next one.
