### ISSUE TITLE
Support for many columns

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#143]
I'm trying to clean up my project 2 code on the dsten server, but it seems to be supporting an older version of Table. In particular, it doesn't seem to support > 255 columns. Do you know if the issue has been fixed, and if the server is up-to-date?

Thanks,
Xinghao

**Comment by papajohn** [comment]
@mDibyo or @SamLau95 , did you fix this column issue already? Have we released since then?

**Comment by mDibyo** [comment]
Column issue was fixed with #101. I don't know if we had a release since then. @SamLau95?

**Comment by SamLau95** [comment]
I think this works now. @papajohn can you verify?

**Comment by pxinghao** [comment]
I can verify that it works on dsten now.

**Comment by SamLau95** [comment]
Great! Closing.
