### ISSUE TITLE
Scatter should label axes correctly

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#146]

**Comment by SamLau95** [comment]
Here's an example of the current incorrect behavior:

```python
>>> a = Table([[10, 20, 30, 40, 50, 60, 70, 80,],
               [2, 13, 8, 5, 3, 2, 0, 1,],
               [3, 10, 13, 12, 2, 0, 0, 0,]],
              ['Age', 'Male Counts', 'Female Counts'])
>>> print(a)
Age  | Male Counts | Female Counts
10   | 2           | 3
20   | 13          | 10
30   | 8           | 13
40   | 5           | 12
50   | 3           | 2
60   | 2           | 0
70   | 0           | 0
80   | 1           | 0
>>> a.scatter('Age')
```
![screenshot 2015-11-24 13 35 26](https://cloud.githubusercontent.com/assets/2468904/11381329/441f1a94-92b0-11e5-8940-2432bcd1a296.png)

As you can see, the x-axis for these scatterplots should be 'Age' and the other column should be the label for the y-axis.

@taylorkmw Do you want to take this on?
