### ISSUE TITLE
Split datascience.py file into smaller, more digestible files

### ISSUE THREAD

**Issue by SamLau95** [dsten/datascience#15]
It's hard to tell at a glance what the `datascience.py` file does since it's getting pretty long (~700 LOC as of this writing). I think we should consider splitting it up into separate files to help with code organization.

**Comment by deculler** [comment]
That would make most sense if we were going to create a simple base class,
such as just the data structure, and layer higher level functionality, such
as plotting, in derived classes.  I could see three such: base, transforms,
viz.  I don't know that more smaller is any more readable.  It is pretty
clean.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by papajohn** [comment]
I think we just make a `datascience` module with an `__init__.py` that loads all of the classes/functions in each one. Proposed file structure:

- `table.py` (most of the current stuff)
- `formats.py` (string formatting — e.g. currency and percentages)
- `maps.py` (new map stuff)
- `sample.py` (re-sampling routines)

I'd still like `from datascience import *` to expose everything (e.g. `Table`) directly.

Note that ideally there is some interaction with tables and maps: we should be able to put maps into table cells

**Comment by papajohn** [comment]
By the way, I think `table.py` (currently `datascience.py`) will stay long, but let's try not to let it grow too much more. 

The only part of `table.py` that could feasibly be moved into a separate file is plotting, but let's hold off for a bit.

**Comment by deculler** [comment]
agree

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley
