### ISSUE TITLE
Adding a new column w/ > 1 and < n_rows changes the table shape

### ISSUE THREAD

**Issue by choldgraf** [dsten/datascience#160]
e.g.

```python
nfeats = 10
data = list(np.random.randn(nfeats, 100))
labels = [string.ascii_lowercase[i] for i in range(nfeats)]
table = ds.Table(data, labels=labels)

# This assigns 10 to all rows under column 'yes'
table['yes'] = 10
print(table.num_rows)

# This will now shrink the table to 2 rows
table['no'] = (10, 20)
print(table.num_rows)
```

**Comment by choldgraf** [comment]
I'm not getting this bug in the dev version of this, so perhaps it is fixed? It now throws a column/label mismatch error

**Comment by deculler** [comment]
That's what you should get.  A Table is a ordered collection of named
columns of equal length.  It is rectangular - like a region of a
spreadsheet or a database table.

Your comments are not correct.  Both assignments set a column in the table
- as long as it is conformant with the table.  Rows are a slice through the
columns.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by choldgraf** [comment]
Agreed that the error is correct. When I originally opened this issue I could take a table of shape (10 x 2) and do `table['new_col'] = [2, 2]` and it would reshape the table to now be (2 x 2). Thus the issue.

This no longer happens in the dev version. It now (correctly) raises an error, so I just wanted to double check all was well before closing this.

**Comment by choldgraf** [comment]
I should mention - I think that people who are using the `pip` version of this repository, and not the dev version, will still encounter this bug.
