### ISSUE TITLE
Can't define a table from a dict (in dev version)

### ISSUE THREAD

**Issue by cboettig** [dsten/datascience#161]
Trying:

```py
ds.Table({"A" : range(0,10)})
```

Throws error:

```py
AssertionError                            Traceback (most recent call last)
<ipython-input-71-01d080f4ca95> in <module>()
      1 ds.__version__
----> 2 ds.Table({"A" : range(0,10)})

/opt/conda/lib/python3.4/site-packages/datascience/tables.py in __init__(self, columns, labels, formatter)
    236         columns = columns if columns is not None else []
    237         labels = labels if labels is not None else []
--> 238         assert len(labels) == len(columns), 'label/column number mismatch'
    239 
    240         self._num_rows = 0 if len(columns) is 0 else len(columns[0])

AssertionError: label/column number mismatch
```

I'm on: 

```py
ds.__version__
'0.3.dev21'
```

@choldgraf confirms that this command throws no errors on `v0.3.14`

**Comment by choldgraf** [comment]
Ah I think I see the problem - when I wrote the guide I was using an old version of `datascience`. It has since been updated and the proper way to construct a table using a dictionary of col: values is with the `from_columns_dict` constructor. E.g.:

`ds.Table.from_columns_dict({"A" : range(0,10)})`

**Comment by cboettig** [comment]
@choldgraf Thanks!  Not sure why the constructor isn't selected by the argument class (any longer), but good to know that works.

**Comment by SamLau95** [comment]
Yeah, unfortunately we made this breaking change... (I wonder who
merged in that
pull request <https://github.com/dsten/datascience/pull/117>)

**Comment by cboettig** [comment]
;-) No worries, don't think anyone expects things to be stable while development is on-going, just trying to grok the logic.  

I do see a lot of the pandas documentation use this `dict` style initialization, which is kind of nice as it is easier to visually match up the labels to the columns than when using the `[values], [labels]` format; so that's why I was hoping to use it here (likewise it parallels the R construction of `colname = values`).
