### ISSUE TITLE
Use plt instead of plots?

### ISSUE THREAD

**Issue by SamLau95** [dsten/datascience#167]
It looks like convention is to use `import matplotlib.pyplot as plt` whereas for
DS8 we've been using `import matplotlib.pyplot as plots`. Is there a reason for
this? If not, I don't see that we need to break from convention since
most docs online use `plt` ([such as the official `matplotlib` docs](
http://matplotlib.org/users/pyplot_tutorial.html)).

@papajohn @henryem @deculler

**Comment by papajohn** [comment]
plt is fine.

**Comment by SamLau95** [comment]
Cool, will use that from now on.
