### ISSUE TITLE
Should we import * in __init.py__?

### ISSUE THREAD

**Issue by SamLau95** [dsten/datascience#169]
Right now, our `__init__.py` has lines that look like:

    from .tables import *

This means that `import datascience` takes a good amount of time to run because it
has to import `Table`, which in turns imports a lot of libraries (specifically,
`abc`, `collections`, `collections.abc`, `functools`, `inspect`, `itertools`,
`urllib.parse`, `numpy`, `matplotlib.pyplot`, `pandas`, and `IPython`).

This could be a concern moving forward since even our `conf.py` with its
`from datascience.version import __version__` line imports all of the above
libraries whenever we make the docs. Specifically, this is causing builds on
http://readthedocs.org/ to break because their systems don't have some packages
installed. (I was experimenting with readthedocs when I discovered this behavior.)

The alternative is to remove all the `import *` lines from `__init__.py`. This means
we'll have to change our existing import statements from:

    from datascience import Table

To:

    from datascience.tables import Table

This is in the style of `numpy`. I think this is important enough to talk about now
because the earlier we decide on this, the less import statements we'll have to clean
up.

@papajohn @henryem @deculler

**Comment by papajohn** [comment]
`from datascience import Table` needs to work. I don't think we should plan
on datascience growing to a heterogenous beast like numpy with a plethora
of sub-packages.

**Comment by SamLau95** [comment]
Sure, thanks for your input.

**Comment by choldgraf** [comment]
Why couldn't you just include explicit imports in your top level __init__.py? I'm generally -1 on doing `import *`, but if you explicitly called `from .tables import Table` in your highest init script, then you could still do `from datascience import Table`, no?

**Comment by SamLau95** [comment]
That would allow `from datascience import Table` and would be slightly
nicer than `import *` but still runs into the issue of having to load all
required libraries when importing datascience.

It doesn't seem like there's a way to get around that and still be able to
do `from datascience import Table` from what I can tell.

I don't think it's a major issue, but if we want to use readthedocs we'll
have to think of some way around it.

On Sat, Dec 26, 2015 at 2:07 PM, Chris Holdgraf <notifications@github.com>
wrote:

> Why couldn't you just include explicit imports in your top level *init*.py?
> I'm generally -1 on doing import *, but if you explicitly called from
> .tables import Table in your highest init script, then you could still do from
> datascience import Table, no?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dsten/datascience/issues/169#issuecomment-167367225>.
>



-- 
Sam Lau
EECS | UC Berkeley | May 2017
(562) 565-4336 | samlau95@berkeley.edu
ᐧ

**Comment by choldgraf** [comment]
Ah yeah, that makes sense to me. Just offering my 2c in case the idea hadn't been considered yet. :)

**Comment by SamLau95** [comment]
No prob, always appreciated!
ᐧ

On Sat, Dec 26, 2015 at 3:04 PM, Chris Holdgraf <notifications@github.com>
wrote:

> Ah yeah, that makes sense to me. Just offering my 2c in case the idea
> hadn't been considered yet. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dsten/datascience/issues/169#issuecomment-167370659>.
>



-- 
Sam Lau
EECS | UC Berkeley | May 2017
(562) 565-4336 | samlau95@berkeley.edu
