### ISSUE TITLE
A few minor issues with the tutorial

### ISSUE THREAD

**Issue by cboettig** [dsten/datascience#171]
Just noticed these, thought I'd make a record.

In beginning example, `cat mydata.csv` should be `cat sample.csv` I think.

Almost all examples seem to use subsetting with square brackets (`t["letter"]`) rather than subsetting with the `values` method,  `t.values("letter")`.  Maybe that's fine but my understanding was that the course was intending to emphasize teaching the latter, at least to start?

**Comment by SamLau95** [comment]
Oops, good catch with the CSV file.

I believe the plan is to teach and use table.values at least initially.
Then, students can think of all operations on tables as method calls.

Thanks for pointing these out. I'll make a note of that above point in the
tutorial.

**Comment by deculler** [comment]
Clearly this is John's call, but I wouldn't head that direction.  Indexing
is such a fundamental concept. They are used to it from excel.  It leads
them to deal with arrays, lists and dictionaries.  And it is so much less
verbose.  I'll watch and see where this goes.

**Comment by a-adhikari** [comment]
I have the same view as David. 
Ani

**Comment by SamLau95** [comment]
I agree that using indexing is much better generally speaking.
However, for students who are just beginning to develop a mental model of
code evaluation I think it's simpler to first think about all operations on
Tables as method calls. Then, they can use bracket notation as a
shorthand. Last semester we taught it the other way around.

I think that's what I'd prefer; I don't want to remove the use of bracket
syntax entirely.

On Tue, Jan 5, 2016 at 8:20 PM a-adhikari <notifications@github.com> wrote:
I have the same view as David.

Ani



> On Jan 5, 2016, at 8:13 PM, David Culler <notifications@github.com> wrote:

>

> Clearly this is John's call, but I wouldn't head that direction. Indexing

> is such a fundamental concept. They are used to it from excel. It leads

> them to deal with arrays, lists and dictionaries. And it is so much less

> verbose. I'll watch and see where this goes.

> On Jan 5, 2016 5:42 PM, "Sam Lau" <notifications@github.com> wrote:

>

> > Oops, good catch with the CSV file.

> >

> > I believe the plan is to teach and use table.values at least initially.

> > Then, students can think of all operations on tables as method calls.

> >

> > Thanks for pointing these out. I'll make a note of that above point in
the

> > tutorial.

> >

> > On Tue, Jan 5, 2016 at 5:03 PM Carl Boettiger <notifications@github.com>

> > wrote:

> >

> > > Just noticed these, thought I'd make a record.

> > >

> > > In beginning example, cat mydata.csv should be cat sample.csv I think.

> > >

> > > Almost all examples seem to use subsetting with square brackets (

> > > t["letter"]) rather than subsetting with the values method,

> > > t.values("letter"). Maybe that's fine but my understanding was that
the

> > > course was intending to emphasize teaching the latter, at least to
start?
