### ISSUE TITLE
understanding use of mixed type/class in Table columns?

### ISSUE THREAD

**Issue by cboettig** [dsten/datascience#173]
My intuition was that every cell in an individual column in a Table object would have the same object type or class, but this appears not to be the case:

```python
from datascience import Table
import pandas as pd
import numpy as np

df = pd.DataFrame({"A" : ["1990-12-01", np.nan, "2015-02-02"]})
table = Table.from_df(df)

## probably a much cleaner way to do this, but here we go:
def cl(x):
    return x.__class__

table.apply(cl, "A")
```

Which shows:

```
array([<class 'numpy.str_'>, <class 'numpy.float64'>, <class 'numpy.str_'>], dtype=object)
```

woah.  Is that really expected? I find it hard to `apply` more interesting functions over a column when I cannot predict the object type.  (Of course in this example the behavior is driven by the presence of missing value being treated as a `numpy.float64` and could be fixed by doing something like `df.fillna("")` first, but I'm just using this to understand when / why a column can have different object types in each row more generally.  That's not possible in other languages I've seen.  

It was also a surprise to see that we do not get the same object if we construct the same table more directly:  

```python
table = Table.from_columns_dict({"A" : ["1990-12-01", np.nan, "2015-02-02"]})
table.apply(cl, "A") 
```

Unrelated, but is there a `Table` method like `apply` that returns a `Table` object instead of an array?  In general, I'd prefer working with a consistent structure as much as possible, and thus would be good to have methods that keep the `Table` object instead of working with the underlying data structures. e.g. looking for the behavior of `pandas`  `df.applymap`: 

```python
df.applymap(cl)
```

**Comment by papajohn** [comment]
It's up to the user to construct sensible columns. Type coercion seems beyond the scope of the `datascience` module.

I think `from_columns_dict` should either be removed or made to behave identically to normal construction. I'll take a look.

**Comment by cboettig** [comment]
Sounds good, thanks.

Re removing: `from_columns_dict`: I'm sure there's good reasons to avoid it, but from my naive perspective it's easier to to make sure you have the labels appropriately matching the columns using that format than it is using the default `Table` init method.  (most docs for `pandas` use the `dict` style initialization, also similar to how R defines column labels).  Having `from_columns_dict` just wrap the `pandas` method and then do `to_df` seems like a good way to make the behavior above consistent and also ease the user's transition to `pandas` when the time comes.

**Comment by papajohn** [comment]
I agree that the default constructor is hard to use. The problem with
python dicts is that they aren't ordered, and that's not something we can
change.
