### ISSUE TITLE
python setup.py test doesn't run the tests

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#174]
I'm not too familiar with `setup.py`. I think `python setup.py test` should execute `py.test`, but right now it does nothing. `make test` currently runs `setup.py`, and so it also does nothing.

**Comment by alvinwan** [comment]
I just added the `tests` dir to the test command. Here's what I get with `python setup.py test`. Does it work for you? I remember having to configure something prior to getting `python setup.py test` to work.

<img width="566" alt="screen shot 2016-01-11 at 1 45 19 pm" src="https://cloud.githubusercontent.com/assets/2068077/12247639/c17a47a0-b869-11e5-849e-3e4969a651a8.png">

**Comment by alvinwan** [comment]
Should be fixed now. A recent setuptools iteration includes automatic detection for tests, so I added a requirement, forcing upgrade to setuptools 19.2.

**Comment by papajohn** [comment]
No, doesn't work for me.

```
$ python setup.py test
running test
Searching for setuptools==19.2
Best match: setuptools 19.2
Processing setuptools-19.2-py3.4.egg

Using
/Users/denero/Documents/workspace/ds/datascience/.eggs/setuptools-19.2-py3.4.egg
```

`py.test` still works, so that's fine, but if that's the standard way to
run tests (instead of `python setup.py test`), then we'll need to put that
in the docs.
