### ISSUE TITLE
Mapping through a table

### ISSUE THREAD

**Issue by deculler** [dsten/datascience#21]
In many cases it would be good to build up a little table and use it to augment another table.  A common case is to map through a table.  For example, you have a table of Parcels.  You have categorized them.  Now you want to map categories to colors.  So you build a little table.

color_map = Table.from_rows([["Residential",'#f1eef6'], 
                             ["Commercial",'#d0d1e6'],
                             ["Industrial",'#a6bddb'],
                             ["Apartment",'#74a9cf'],
                             ["Public",'#2b8cbe'],
                             ["Other",'#045a8d']], ("Category", "Color"))

The old join did a left outer join; thus, this would just work.  The new one does an inner join - you only get one row per match.  You can build it up with indexed_by, but it is pretty ugly because it is dealing with the possibility of multiple matching entries.  If we implement lookup we can get this case.  Or do we want to offer a richer join?

**Comment by alvinwan** [comment]
We could add a boolean param; all I need to do is modify [this line](https://github.com/dsten/datascience/blob/master/datascience/table.py#L361) to say:
```
if is_outer_join ^ label in other_rows:  # where ^ is xor
```

**Comment by deculler** [comment]
Great that there is an easy code change.  Ain't Python incredible.

I know John has some thoughts on this and will want to weigh in.  Having
the option of the outer join (and left will be the natural choice) looks
like it will be very important.  I'm not a real big fan of passing
parameters in to change method behavior - like the flags to numpy.unique.
In this case, it may be more natural for _join to take the flag and join
and join_outer to pass it in.

Related to this issue is our perspective on rows.  We have the ability now
to get a collection of Rows.  And the object holds onto the table.  But if
you index it you get a Row which loses that.  In the early version the
analog gave you a dict with keys being the column labels.  This ensured
compliance with the structure of the table and made selection of cells
within the row natural.  I do realize that anything you can do in a Table
context you can also do at the Python / numpy level.  So the question is
how much of that do you need.

I must admit, I'm a little uncomfortable with the new documentation line.
Table is not and ordered_dictionary.  It is implemented using them.  But it
has semantics that are in many ways simpler and more orderly than that more
primitive object. Seems that this is partly what is floating around in the
question of what Table.rows[index] returns.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by deculler** [comment]
Looks like [this one](https://github.com/dsten/datascience/blob/master/datascience/table.py#L363) is where the action is.  Left outer would iterate through rows, right out through other other_rows and outer through both.  My proposal is to only do left outer.  That allows the right table to be a simple functional mapping.  Take a table and transform a column by looking up its value in another table and bringing in the rest of the rows.
