### ISSUE TITLE
Join tests broken

### ISSUE THREAD

**Issue by alvinwan** [dsten/datascience#22]

**Comment by deculler** [comment]
This may be a result of going to left outer join.  If you look at the
berkeley_tables in demo you'll see why it is so nice to have.  For the case
where there is a unique item in each table, these all are the same.  I do
think the asymmetry is quite natural.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by alvinwan** [comment]
@deculler I see I see. However, it looks like the left outer join isn't preserving unmatched rows from the "left" (first) table.

Output of table.join('points', table2)
```
E      points | letter | count | totals | names
E      2      | c      | 3     | 6      | two
E      2      | b      | 3     | 6      | two
E      1      | a      | 9     | 9      | one
```

where table is:
```
	letter | count | points
	a      | 9     | 1
	b      | 3     | 2
	c      | 3     | 2
	z      | 1     | 10
```

From `table`, the last row is missing. Right now, it looks like it's still an inner join, except with duplicate matches in the indexed column, repeated.

Let me know if I'm missing something, or if I should fix it.

**Comment by alvinwan** [comment]
I went ahead and changed `join` so that it included rows in left and not in right, amended tests.

**Comment by deculler** [comment]
The result only includes matched rows.  The difference we were after is
that a row in the right might match multiple rows in the left.  There would
be a row in the result for each left row that had a matching right.  The
more general form would have a row in the result for each pairwise match.

Thanks for looking into this.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by alvinwan** [comment]
Ah, I see. Sounds good.

Yep.
