### ISSUE TITLE
Table help is incorrect

### ISSUE THREAD

**Issue by davidwagner** [dsten/datascience#24]
`help(Table)` gives the following example of how to use a `Table`:

     |  >>> letters = ['a', 'b', 'c', 'z']
     |  >>> counts = [9, 3, 3, 1]
     |  >>> points = [1, 2, 2, 10]
     |  >>> t = Table([('letter', letters), ('count', counts), ('points', points)])

However copy-pasting that into Jupyter goes the following error message:

    ---------------------------------------------------------------------------
    AssertionError                            Traceback (most recent call last)
    ...
    /usr/local/lib/python3.4/dist-packages/datascience/table.py in __init__(self, columns, labels)
    ---> 46         assert labels is not None, 'Labels are required'

**Comment by alvinwan** [comment]
Sorry, table syntax changed, and I never updated it. Fixed:

```
letters = ['a', 'b', 'c', 'z']
counts = [9, 3, 3, 1]
points = [1, 2, 2, 10]
t = Table([letters, counts, points], ['letter', 'count', 'points'])
print(t)
```
