### ISSUE TITLE
Travis + Coveralls

### ISSUE THREAD

**Issue by alvinwan** [dsten/datascience#25]
@papajohn Can we use [Travis](http://travis-ci.org) and [Coveralls](http://coveralls.io)? I tried but don't have the permissions to set them up. It should be just a few clicks; I can add the badges afterwards.

**Comment by alvinwan** [comment]
@papajohn To add to the wishlist, can we have a wiki too? I think we need a place to document `Table` and `Map` features.

**Comment by papajohn** [comment]
I've had bad experience with wikis. They rarely seem to represent the current truth. Feel free to add feature descriptions to readme files.

**Comment by papajohn** [comment]
Ok, I've given permissions to coveralls and travis. @alvinwan can you configure them to your liking?

https://coveralls.io/github/dsten/datascience
https://travis-ci.org/dsten/datascience

**Comment by alvinwan** [comment]
Sure, that makes sense. I'll add to the README instead then.

Awesome, thanks. I'll add the configs.
