### ISSUE TITLE
Where method doesn't handle invert or conjunction well

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#30]
We should consider adding one of these, because `where` is currently lacking.

`.where(column_label, fn)`
`.where(column_label, value, compare_fn)`
`.where(column_label, value, not_equal=True)`

Top one seems most general, so that's probably the way to go, but it requires understanding higher-order functions.

The problem is that if I want to say `n != 2 and m < 4` for columns `n` and `m`, neither of the following work.

`t.where(t['n'] != 2).where(t['m'] < 4)` fails because `t['m']` is unfiltered and has the wrong length

`t.where(t['n'] != 2 and t['m'] < 4)` fails because `and` doesn't work with numpy arrays

The only working solutions currently are both ugly:

`t.where(numpy.logical_and(t['n'] != 2, t['m'] < 4))`

```
u = t.where(t['n'] != 2)
u.where(u['m'] < 4)
```

**Comment by alvinwan** [comment]
What about the following syntax?
```
t.where(t['n'] != 2 & t['m'] < 4)
```
Note to self: [functions to override](https://docs.python.org/3.4/reference/datamodel.html#emulating-numeric-types)

**Comment by papajohn** [comment]
Not bad, actually. It's kind of a hack to repurpose bitwise operators for
this, but maybe it's our best option.

We can't override operators on numpy arrays.

-John

**Comment by deculler** [comment]
I agree that we need to work a bit more on where.  It would be nice to be
able to do this simplest thing simply - select rows where a column as a
value.

Ultimately, being able to pass in the function ought to be there, even if
it is something that you grow into.  But it probably wants to be more than
a function over one column, e.g., where A < B.

Aren't the numpy policies on boolean operations changing?  Seems like we
get warnings about upcoming changes.  Is there a path they are heading that
we could utilize?

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by papajohn** [comment]
It's already the case that `where` can select non-zero values (just pass a
column label) or values that equal some value (pass a column label and a
value).

I don't see a warning about future changes (maybe a version issue). If you
come across it again, can you paste it in here?

**Comment by deculler** [comment]
will do

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by alvinwan** [comment]
We can now use the following:
```
t.where(Q(t['n'] != 2) & Q(t['m'] < 4))
t.where(Q(t['n'] != 2) | Q(t['m'] < 4))

# albeit a pointless query... here's how to combine operators
range1 = Q(t['n'] != 6) | Q(t['m'] < 4)
range2 = Q(t['n'] != 2) & Q(t['m'] < 4)
t.where(Q(range1) | Q(range2))
```
*Python's built-in order of operations doesn't allow us to do this without the wrapper `Q`... even if we could wrap numpy arrays to override operators.
