### ISSUE TITLE
Pivot needs to support multiple rows

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#31]
I already ran into an example where I needed multiple rows in a pivot. I had to join and then split a column to get what I wanted, which was gross. We need to support something like

`t.pivot(column, [row0, row1], value, ...)`

**Comment by mDibyo** [comment]
Working on this. Not able to/couldn't figure out how to assign it to myself...

**Comment by alvinwan** [comment]
@papajohn has to add you to the org. Couldn't find you in the assignee list on the right.

**Comment by mDibyo** [comment]
Added to the organization. Thanks Alvin!
