### ISSUE TITLE
Resampling-based Hypothesis Testing

### ISSUE THREAD

**Issue by alvinwan** [dsten/datascience#34]
@mijordan3 :

>It would be good to have both bootstrap-based hypothesis testing (where
column A is resampled n times
with replacement and column B is independently sampled n times with
replacement), and permutation
testing (where column A and column B are put together in a single long
column, a random permutation
is made of that column, it is split in the middle into two new columns, and
the statistic is computed on
those two columns).

@SamLau95 I can expand `sample` functionality. Would the following syntax work?

```
def table(self, k, with_replacement=False, columns=[], random_permutation=False)
# columns is a list of column names - if set, with_replacement 
# must be a list of the same length OR random_permutation must
# be true
# if columns and with_replacement are both lists, and r_p is True,
# assert error (don't know what to do)
```

- [ ] independent column sampling
- [ ] permutation sampling

**Comment by SamLau95** [comment]
I haven't dived into the table code myself so I trust your judgement! Any pointers on high-level ideas would be awesome. I'll get started with permutation sampling.

**Comment by papajohn** [comment]
I think the signature of one method should be `def sample(self, k=None, with_replacement=False)` and it should sample full rows (all columns). After that, `select` can be used to select particular columns. If `k=None`, then as many rows as are currently in the table are sampled. So `sample(with_replacement=True)` would give a random permutation.

**Comment by mijordan3** [comment]
I agree with keeping column selection separate.

Don't you mean "sample(with_replacement=False) would give a random
permutation"?

Although I can think of uses for random column sampling in other contexts,
for this course random
row sampling will surely suffice.

M

**Comment by papajohn** [comment]
Yes, corrected my comment to "sample(with_replacement=False) would give a
random
permutation"

**Comment by alvinwan** [comment]
Implemented `k=None` default for `sample`, and master updated.

@SamLau95 Cool, looks like the professors a smarter design for this. Just let me know if I can help with anything.

**Comment by SamLau95** [comment]
@mijordan3 Could you clarify a bit? For a table like this:

```
letter | count
a      | 9
z      | 1
b      | 3
c      | 3
```

Is this a valid sample for a bootstrap-based hypothesis test with `n = 2`?

```
letter | count
a      | 3
a      | 1
```

I'm a bit confused by what we should output since I'm not sure what you mean by sampled n times. When you refer to column A and B, does that mean this only works for tables with two columns like my example?

And for a permutation test, if we have two original samples that look like:

```
s1   | s2
1    | 5
1    | 5
1    | 5
1  
1  
```

Then does a valid permutation test sample look like this?

```
s1   | s2
1    | 1
1    | 1
5    | 5
5  
1  
```

(This is also not supported by our current Table structure since the column lengths are different but is fine for a permutation test.)

**Comment by papajohn** [comment]
We'll probably have to discuss, but I think we don't want table methods for
performing hypothesis tests. Instead, we want a separate batch of functions
that implement these tests. The way I'd design this part of the course is
to have only a `sample` method on tables that supports re-sampling and
permutation, then save things like comparing stats on two halves of a
permutation for a separate function.

-John

**Comment by SamLau95** [comment]
Cool, so I'm gonna table this for now. Feel free to ping this again when the time comes.

**Comment by SamLau95** [comment]
@papajohn Does this issue still need addressing since we have `Table.sample`?

**Comment by papajohn** [comment]
I'll close for now. I think we'll revisit the syntax for performing a permutation test before next semester, because it's a little too involved now.
