### ISSUE TITLE
Histograms "bins" parameter should be able to take a list of bin endpoints for unequal-sized bins

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#36]

**Comment by SamLau95** [comment]
@papajohn Is this for the `hist` method or for `pivot_hist`? (A quick explanation of the difference between the two would also be much appreciated!)

**Comment by papajohn** [comment]
Good question. This change refers to `hist`. `hist` draws a histogram for
each column (perhaps overlaid onto one chart).

`pivot_hist` may not be long for this world. It's equivalent to the
following for loop on a two-column table `t` with columns `a` and `b`,
except that it bins in the same way for every subplot and supports
overlays. I'd like to generalize it somehow, but haven't figured out the
right way yet.

```
for v in np.unique(t[a]):
  t.where(a, v).select([b]).rename(b, v).hist()
```

**Comment by papajohn** [comment]
By the way, I think this change may not be a change at all. The underlying `matplotlib.hist` method takes an array of bins or an integer bin count. If you find that there's nothing to change, just close the issue.   http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.hist

**Comment by SamLau95** [comment]
Looks like the underlying `hist` method has this functionality! Closing.
