### ISSUE TITLE
Table does not seem to support more than 255 columns

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#46]
Here's a piece of code that triggers this issue:
```
lyricsTable = Table.read_table('http://eecs.berkeley.edu/~xinghao/ds10data/lyricsTable.csv')
lyricsTable
gives an error of
  File "<string>", line 12
SyntaxError: more than 255 arguments
```

If I used a smaller table (with 104 columns instead of 5004), the error goes away:
```
lyricsTable = Table.read_table('http://eecs.berkeley.edu/~xinghao/ds10data/lyricsTable_part.csv')
lyricsTable
```

**Comment by papajohn** [comment]
I think the problem is my overuse of `*args` syntax. Probably we can fix it just by isolating the problem and passing arguments a different way.

**Comment by deculler** [comment]
Be nice to handle it gracefully, but ...

5004 by what?  Thousands of lines?  That's a mighty table.  5004x1 ???

255 columns is perhaps a constraint if you think of it as a matrix.  But if
it is words and counts it should be two columns anyways.

**Comment by papajohn** [comment]
These are counts of 5000 different words. Our table representation doesn't
do sparse matrices. It also doesn't handle 5000 columns very gracefully —
we'll have to think about that a little.

**Comment by deculler** [comment]
But it is happy with columns of 5,000 entries, depending on how ordered
dict handles sparsity.

The natural view here is that each song is represented by a feature vector
of a bunch of words.  (5k is a BIG dictionary for lyrics).  You would
expect a 'word' column and one per song.  And the natural thing to do would
be to build the dictionary from songs, filtering on some frequency of use.
As more songs are considered, take the union of dictionaries.  Nice
alternative to join - a kind of open world, rather than closed world
perspective.  At any point, songs could be collapsed into genre, thereby
managing the number of columns.

In part we are seeing the distance between the mathematical sparse-matrix
view of the world and one that rests heavily on interacting with a useful
representation.

20,000 songs of 5,000 words - 100 million cells.  Very sparse indeed.  Not
immense, but not trivial either.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by mijordan3** [comment]
Hmm, I'm used to seeing all kinds of data science problems with many tens
of thousands or even hundreds
of thousands of columns.  In some cases the matrices are sparse (along the
rows) but definitely not in all cases.

If the table implementation can be made to work for 5000 columns then
that's OK for this class, but if you
guys have ambitions of a more widely-used piece of software, educational or
beyond, then a limitation like
this would be a show-stopper...

M

**Comment by mDibyo** [comment]
Is this still an issue I should look at?

**Comment by papajohn** [comment]
Yes, it's still an issue that we need address very soon.

**Comment by mDibyo** [comment]
I tracked down the problem.
tables.py, Table.as_text, line 849
tables.py, Rows.__getitem__, line 1317
... goes into python code. It is not a problem with our code. It seems to be a known problem with namedtuple (http://stackoverflow.com/questions/18550270/any-way-to-bypass-namedtuple-255-arguments-limitation). We can probably work around it and in future, consider submitting a fix to python. Looking further into this...

**Comment by papajohn** [comment]
It was confusing to students that we used a namedtuple to represent a row,
b/c it gets displayed in such a wonky way. A plain tuple or list would
probably be better for a row representation, in hindsight. Something to
consider.  I think array is not idea b/c columns tend to have different
value types.

**Comment by mDibyo** [comment]
I can think of a few alternatives:
OrderedDict:
- Pros: can be added quickly, still has column names
- Cons: wasteful of space, not really the right representation for a row

A subclass of collections.UserList/list:
- Pros: can be whatever we want to make of it
- Cons: will take more time to get the implementation right

I'd go with the second. As @papajohn mentioned, we don't need column names, and even if we did, we can add an attribute on the list to access column name(s).

**Comment by mDibyo** [comment]
A completely new implementation might work too. Consider a class factory, that creates a class for the rows of each table with column labels available as attributes (similar to what the namedtuple is doing now). It would use `__slots__` to limit memory usage. @papajohn, what do you think?

**Comment by deculler** [comment]
We don't need column names in the row data representation, but presumably
we would still have them in the Row object by retaining the reference to
the enclosing table.  So if you are in here working hard seems like we may
want to include indexing by column label, not just int.

**Comment by papajohn** [comment]
I think we give up on column labels and just use a plain tuple to represent
a row, indexed by column index. The only change is that namedtuple ->
tuple.

**Comment by mDibyo** [comment]
What about finding the value for a specific column in a row (especially when there are a large number of columns)? Should there be a wrapper on tuple that allows for that?

**Comment by mDibyo** [comment]
I have added a PR for this ^

**Comment by mDibyo** [comment]
closing this.

**Comment by pxinghao** [comment]
I'm being very dumb on this, but can someone explain how I should update my local machine to pull this update?

**Comment by papajohn** [comment]
pip install datascience==0.3.dev21
