### ISSUE TITLE
Drop row

### ISSUE THREAD

**Issue by pxinghao** [dsten/datascience#47]
The current Table API supports take (for rows), but appears to lack the functionality to drop rows. While it is possible to work around this by constructing my own complement, it would be more elegant to directly support these operations.

This is in the context of doing cross-validation, where we typically drop a small number of rows to construct the test set.

[This issue should be labeled as enhancement, but I can't seem to figure out how to do that.]

**Comment by papajohn** [comment]
I support this change.

**Comment by SamLau95** [comment]
This behavior is implemented by [`Table.split`](http://data8.org/datascience/_autosummary/datascience.tables.Table.split.html#datascience.tables.Table.split).

**Comment by SamLau95** [comment]
Closed by accident! We don't have a method that accepts row indices and outputs a new table without those rows.

**Comment by mDibyo** [comment]
How about `Table.except(range(1, 6))`?

**Comment by mDibyo** [comment]
Ping

**Comment by papajohn** [comment]
Sounds fine to me.

**Comment by mDibyo** [comment]
Forgot that `except` is a reserved keyword. Going with `Table.except_`

**Comment by SamLau95** [comment]
Or maybe `Table.without`?

**Comment by papajohn** [comment]
No underscores please.

**Comment by mDibyo** [comment]
Decided to go with `Table.exclude` (and `_Excluder`) to go with the imperative `Table.take` (and `_Taker`).
