### ISSUE TITLE
Methods need better documentation

### ISSUE THREAD

**Issue by SamLau95** [dsten/datascience#50]
When working with the datascience package, I spend a lot of time trying to figure out how the methods work since the docstrings aren't super helpful — some methods require the table to be a certain shape, others require the table values to be numbers, others strings. None of these details are mentioned in some important methods like `hist` and `barh`.

In addition, to find out whether the package has the functionality I want (eg. whether I can group a table of years by decade) I have to browse the methods one by one, trying to keep a lot of things in my head about what methods are available.

I imagine I'm running into a majority of these issues because most of this code wasn't written by me. However, this will be the case for our students so IMO the earlier we can work on this the better.

**It'd be very helpful to 1. Improve the docstrings and 2. Have easily navigable documentation (probably generated from docstrings using something like [Sphinx](http://sphinx-doc.org/)).**

A great place to start would be the plotting functions, since those seem to be the most finicky and most commonly used.

**Comment by henryem** [comment]
The first lab on histograms will be next Wednesday (9/9), so this is somewhat urgent.  Even to design the lab over the next week, we'll need to understand what functionality is available.

**Comment by papajohn** [comment]
Let's make progress! I've assigned Sam to get started. When you get stuck, ping @alvinwan and me. It's much easier to write effective docs if you're not the one who designed the code, I think.
