### ISSUE TITLE
Add wrapper for boxplot function

### ISSUE THREAD

**Issue by SamLau95** [dsten/datascience#53]
Conveniently, it turns out that [matplotlib has boxplots](http://matplotlib.org/examples/pylab_examples/boxplot_demo.html), which is something @a-adhikari wanted for an upcoming lecture on visualizations.

We should write a `Table.boxplot` function that essentially wraps the matplotlib function ASAP.

**Comment by SamLau95** [comment]
Hey @taylorkmw , wanna take on this issue? Go ahead and assign yourself to the issue if so!

**Comment by SamLau95** [comment]
Hey @taylorkmw ! Any updates on this?

**Comment by taylorkmw** [comment]
Please take a look at my pull request. Sorry for the long wait!
