### ISSUE TITLE
CurrencyFormatter broken?

### ISSUE THREAD

**Issue by rjboczar** [dsten/datascience#56]
M(N-)WE:

from datascience import *
%matplotlib inline
import numpy as np

tab = Table(labels=["money"], columns=[[1.,2.,3.]])
tab.set_format("money", CurrencyFormatter)

**Comment by rjboczar** [comment]
Would like to have this for lab 4, if possible.

**Comment by papajohn** [comment]
I'm maxed out this week — Alvin or Sam?

**Comment by SamLau95** [comment]
Same for me. @alvinwan ?

**Comment by mDibyo** [comment]
I am willing to take it on. Is that ok?

**Comment by papajohn** [comment]
That's great!
