### ISSUE TITLE
Barh doesn't guarantee chart order

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#58]
Charts for columns might come out in the wrong order, which is surprising. They should be rendered in column order.

**Comment by SamLau95** [comment]
@ericz82 , wanna take this one?

**Comment by ericz82** [comment]
Sure

**Comment by ericz82** [comment]
Hmmm... I ran a few tests but the charts seem to be rendering in the order of the columns, unless I am supposed to looking at something else (maybe the rows)
[Untitled.html | uploaded via ZenHub](https://files.zenhub.io/5611b51065668d7d71c76ae5)

**Comment by SamLau95** [comment]
Sorry for the confusion — we're referring to the fact that the rows don't get plotted in the right order. In your uploaded example, the bars should be a, b, c, then z (but they're z, c, b, then a).

**Comment by SamLau95** [comment]
Closed by #98. In the future, you can put a line like Resolves #98  in your PR / commit message and Github will autoclose the issue :)
