### ISSUE TITLE
CSS for docs not working; suspect DNS issue

### ISSUE THREAD

**Issue by SamLau95** [dsten/datascience#59]
http://data8.org/datascience/

Shows that the CSS isn't loading. I suspect this is because dsten.github.io is getting automatically redirected to data8.org but the asset files aren't being redirected properly. @papajohn any thoughts?

**Comment by papajohn** [comment]
How did you publish? I would suggest just checking the whole docs directory
into https://github.com/dsten/dsten.github.io unless that poses a problem.
All the files should be served then.

**Comment by SamLau95** [comment]
Oh gotcha. I pushed to the gh-pages branch on the datascience library
itself. Will toss the docs directory into the dsten repo instead.

**Comment by SamLau95** [comment]
Issue still persists on the dsten.github.io repo. Closing the issue on this repo and will investigate.
