### ISSUE TITLE
Marker.show() throws error

### ISSUE THREAD

**Issue by davidwagner** [dsten/datascience#63]
I tried to use the Maps demo from text/demos/MapsDemonstration.ipynb.  I can't make it work for me.

When I try to create a Marker, I get an error.  In particular, I can do

    m = Marker(37.78, -122.42, 'San Francisco')

with no error, but then when I do

    m.show()

I get a traceback:

    TypeError: simple_marker() got an unexpected keyword argument 'popup_on'

Same if I type just

    m

into an input cell.

**Comment by papajohn** [comment]
The datascience library assumes `folium==0.1.5`, which was the default when we set up the course infrastructure. I think the `folium` library default has since incremented a version and changed keyword arguments.

If you run the following from a notebook, it might fix the problem...

`!pip install folium==0.1.5`

**Comment by papajohn** [comment]
At least in my browser, none of the demos in `demos/MapsDemonstration.ipynb` work anymore, even with the latest version of `datascience`, when using `folium` 0.1.5. It looks like `ds8.berkeley.edu` was upgraded at some point. I think we'll have to do some debugging before maps rendering is stable again. I can try later today.

**Comment by deculler** [comment]
David,
  You'll want to look at the higher level demos in
https://github.com/dsten/text/blob/master/demos/berkeley_tables.ipynb and
some of the other demos.  That demo only shows the map class.  It was later
integrated into tables, avoiding the lower level stuff.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by davidwagner** [comment]
Thanks, David.  Yes, I've been cribbing from those -- they're still broken.  I think the version of folium got upgraded and has caused this to break.

**Comment by ryanlovett** [comment]
I was asked yesterday to upgrade to datascience 0.3.6. Do you want to
downgrade? If so, which version?

Ryan, from my phone
