### ISSUE TITLE
Overlain histograms need to have the correct bin widths; overlap instead of side-by-side

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#65]

**Comment by papajohn** [comment]
I think the key here is to switch to `histtype='stepfilled'` whenever `overlay` is true, then come up with some sensible defaults for transparency. 

This image is representative of what Ani wants:

![](https://bpattonmth332.files.wordpress.com/2012/02/mth332pic3bp.jpg)

She thinks we don't need to compare more than two datasets in a single chart.

**Comment by deculler** [comment]
Agree
