### ISSUE TITLE
No clean way to count duplicate items in a Table, with Table API

### ISSUE THREAD

**Issue by davidwagner** [dsten/datascience#68]
Goal: Given a table T and a column C, build a new table that has one row for each unique value in T.C along with a count of the number of times that value appears in T.C.

I was not able to find any clean way to do this within the Table API.  Should this be doable using Tables, without leaving Table space and going back to arrays and raw Python?

Here is the solution I came up with:

    from collections import Counter
    c = Counter(origtbl['column_label'])
    t = Table.from_rows(c.items(), ['column_label', 'count'])

Not so terrible if you know Python idioms, but also probably not so discoverable for students.  Should there be an API in Table that's accessible to students that allows performing this kind of task?  Or some suitable generalized primitive, which is enough to solve this problem?

**Comment by deculler** [comment]
We removed this operation from the class because it is pretty easy to get
with numpy.unique.  You need to ask it for both unique values and the map.
Absolutely important so we should have the example.

**Comment by davidwagner** [comment]
Cool.  Thank you.  Note to future self: `np.unique(x, return_counts=True)`

**Comment by deculler** [comment]
Here's the example

T = Table([['A','A','B','C','A']],['letters'])
labels, counts = np.unique(T['letters'],return_counts=True)
R = Table(list(counts),list(labels))
