### ISSUE TITLE
Minor documentation bug in Tables summary of methods

### ISSUE THREAD

**Issue by davidwagner** [dsten/datascience#75]
The summary of methods lists the first constructor as:

    Table([columns, labels, formatter])

This has a typo: it should be

    Table(columns, labels, formatter)

You need to pass 3 args (or 2 args), not 1 arg that's an array of length 3.

**Comment by SamLau95** [comment]
Actually, that (definitely confusing) syntax in the documentation means that Table takes three optional arguments named `column`, `labels`, and `formatter`, not that the Table constructor takes in a list. See the docs for `Table.sort` for another example of this syntax.
