### ISSUE TITLE
Let's phase out the usage of __getitem__ and __setitem__

### ISSUE THREAD

**Issue by SamLau95** [dsten/datascience#80]
The usage of these methods is a constant source of confusion for students, especially those that haven't programmed before. Many students are often confused about the usage of brackets versus parentheses. For example, whereas we first introduce bracket notation for lists and arrays using something like:

    my_array[0]
    my_array[2:5] # Slicing

For tables, all of a sudden they have to use strings inside of the brackets.

    my_table['Salary'] # Why?

In addition, we can't use slicing for obvious reasons to us but not to students.

**I think table usage would be much simpler and more consistent if the only way to access/modify values was through method calls.**

Students also mix up the usage of `__getitem__` and `select` — the first returns an array of values, the second returns a new table, and students basically have to memorize that fact. I think that if we taught them to use a method called something like `get_column_values` instead that there would be less confusion.

Regarding `__setitem__`, it is confusion to students that there is an `append` method that gets called to add rows but no similar method for columns. Instead, a largely mysterious assignment using bracket notation is needed.

    my_table['New Column'] = [some values...]

This makes sense to use because we commonly use dictionaries, but students have never used dicts before and so this is another thing they have to keep in their heads as they code.

Students basically have to memorize:

- Brackets on their own create lists.
- Use integers to retrieve items when using bracket notation for lists/arrays.
- Use integers + brackets to assign values for specific indices for lists/arrays.
- Use strings to retrieve values as an array when using bracket notation for tables.
- Use strings + brackets to create new columns for tables.

Even my strongest students struggle with the syntax of parentheses vs. brackets, and I think that their confusion is very justified given how inconsistent and seemingly arbitrary the usage of brackets is. (As icing on the cake, we can't document  `__getitem__` and `__setitem__` in the online docs because students don't know that these two methods are syntatic sugar for bracket notation.) We can do away with a lot of this by just replacing them with actual methods.

I would like to:

- Add a method called `get_column_values` that behaves like `__getitem__`.
- Add a method called `add_column` that behaves like `__setitem__`.
- Add a deprecation message when `__getitem__` and `__setitem__` are used, telling users to use the new methods instead.
- Remove the usage of `__getitem__` and `__setitem__` where we can (mainly in the text).
- Next semester, pretend they never existed.

Any thoughts on this? @papajohn @henryem @rjboczar @alvinwan

**Comment by papajohn** [comment]
I'm fine with adding methods that are redundant with item selection/assignment. We can even teach those. 

Let's not remove or deprecate anything though.

`get_column_values` is way too long for a common operation that appears inside tons of nested expressions. maybe `values_for` or just `values`.

**Comment by deculler** [comment]
I absolutely support John's view on this.  Students in this class are just barely learning about arrays and haven't let learned about dicts.  But the ability to use [colname] is huge.  Tables has a role far beyond precisely this class. And it would be a terrible shame to push them back to thinking only about arrays index by position.  Dictionaries are incredibly powerful.  Ordered ones even more so

In any case, students should not be thinking about __setitem__ and __getitem__.  If there is an underscore they should not even know about.

However, we do need the alternate form to add a column.  Amusingly we once did, but eliminated it for _setitem (which happens to be beautiful).  As it currently stands, we have no way to set a column from a column in an existing tables AND carry over the formatter.  The analog of append for columns would be very attractive.  col_append (or whatever) it is called could take sequence of columns or a table (much like append).  In the latter case, it could retain the formats and any other attributes of the appended columns.

**Comment by deculler** [comment]
This item may need to be reopened.  The use of labels to access columns of tables has now disappeared entirely from the documentation.  See http://data8.org/datascience/tables.html

I am STRONGLY against losing t['label'].  It was one of the most critical concepts that John introduced in versions over the summer.  It makes it a proper container and it make it natural to go back and forth between the world of arrays and tables.  It provides a gentle step toward understanding dicts with is absolutely essential that they come to feel comfortable with - eventually.  We use it everywhere because it is a beautiful way to address problems.  It also provided a tie back to what students experience in excel.

I don't know what the student concern was that led Sam to want to remove the ability to index columns, but whatever that is we should address it in the pedagogy of the particular course, not by deprecating their use in tables.

It was fine to introduce .values as an alternative.  And the ability to index did not disappear from the class.  But it did disappear from the documentation.  That was not the intention and John may have missed that in closing the issue.

**Comment by SamLau95** [comment]
@deculler 

There's a bug right now with the docs where the autogenerated docs for `values` and `append_column` aren't appearing online properly. I'm looking into it right now.

Actually, using `t['label']` was never in the documentation in the first place. Adding `Table.values` and `Table.append_column` strictly increased the amount of documentation available about Table methods. In fact, the usage of `t['label']` is documented for the first time in `Table.values` (see https://github.com/dsten/datascience/blob/master/datascience/tables.py#L210-L236)

**Comment by deculler** [comment]
ahh, my bad.  I guess I never noticed that because we didn't have your
lovely documentation before. Maybe this is part of why folks found it
confusing.  They red the docs!  Is there something we should do so that it
does show up there?  It is well represented in the demos.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by SamLau95** [comment]
No worries; I had some concerns with documenting `__getitem__` and `__setitem__` in the docs since students wouldn't know that these are magic methods to use dict-like syntax.

Because of that, my original idea was that we would document that in the Tables tutorial (which has yet to be written at http://data8.org/datascience/tutorial.html).

Another idea is to just explicitly state at the top of the docs for `Table` to look at the docs for `values` and `append_column` for bracket notation usage.

**Comment by deculler** [comment]
Tutorial is a great idea.  Of course, there is a bunch of great stuff in
the lab materials. Also, larger tutorial material is now in
dsten/text/demos.  But it looks like that repo is not public, so it is hard
for people to use it.  Perhaps we can bootstrap the tutorial with that, or
at least have an examples directory.

Seems like we could tackle the doc issue by putting an example of a table
in the text section at the top, before all the auto-generated
documentation.  It might be right at the top before the disclaimer.

A table is an ordered collection named columns.  Create one.  Access a
column.  Set a column. Print it.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by SamLau95** [comment]
This conversation looks like it's basically wrapped with these conclusions:

- We added `Table.values` and `Table.append_column` and aliased `__getitem__` and `__setitem__` to them.
- We will not deprecate the magic methods.
- But the magic methods usage will be documented in the Table tutorial (being written, see #111 )
- Students might eventually be taught the regular methods first to keep all operations on tables consistent (eg. using a method call). This decision TBD.

Feel free to comment further / make a new issue if any of these need more discussion.
