### ISSUE TITLE
Need a better way to define an empty table

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#88]
`Table([[]], ['sample'])` is too clunky. Maybe `Table.empty(['sample'])`. Thoughts?

**Comment by mDibyo** [comment]
`Table(['sample'])` could work too if we distinguish between lists and strings. It would make the documentation more complicated, but I think I can make it work, by making it like matlab documentation (eg. http://www.mathworks.com/help/stats/randsample.html).

**Comment by mDibyo** [comment]
That said, `Table.empty(['sample'])` is probably simpler to code up and simpler to use/document.

**Comment by papajohn** [comment]
I like it. I think you don't need to assume column labels are strings
(though that's assumed elsewhere) — just count the number of arguments that
are None.

**Comment by mDibyo** [comment]
I am worried about the use case:
```python
t = Table({'letters': ['a', 'b', 'c'], 'counts': [9, 3, 1]})
```
The case where we are initializing with a dict. So, what needs to be done is distinguish between a list and a dict, to distinguish this from `Table(['letters', 'counts'])`?
Or do we not want to go there, because it would become too complicated?

**Comment by papajohn** [comment]
Forgot about initializing from a dict... I don't seem to use that much in
practice; perhaps we just move that functionality to a Table.from_dict
static method.

**Comment by mDibyo** [comment]
SG. Will get a PR ready.

On a related note, would it be too bad to then switch the args order to `Table(labels, columns)`? It seems like the right thing to do, but we could wait till the end of the semester before making that change.

**Comment by papajohn** [comment]
Yep. Let's file an issue and switch at end of semester.

**Comment by SamLau95** [comment]
I'm actually for the idea of just making a new `Table.empty` method instead of modifying the original since it seems to keep the `Table` constructor API a bit cleaner, but I don't feel too strongly about it so it's up to you.

**Comment by mDibyo** [comment]
After trying quite a bit to make it work, I feel that a Table.empty method is better too. Python, unlike matlab eschews variable argument ordering, and making it do otherwise felt wrong.

I created a PR for it. I have also extracted out a Table.from_columns_dict method. This has greatly simplified the documentation for Table.
