### ISSUE TITLE
Need a better way to extract the contents of one-row tables

### ISSUE THREAD

**Issue by papajohn** [dsten/datascience#93]
After `t.sum()` or some other reduction to a single row, it's messy to access the contents of the result using `t.rows[0]...`.

**Comment by mDibyo** [comment]
how about the property t.row0? It's only slightly cleaner, but requires less of the shift while typing associated with []'s.
```python
@property
def row0(self):
    return self.rows[0]
```

**Comment by papajohn** [comment]
Nice idea. How about

```
@property
def row(self):
    assert self.num_rows == 1, 'Table has more than one row'
    return self.rows[0]
```

**Comment by mDibyo** [comment]
That makes sense.

**Comment by mDibyo** [comment]
Closing this following resolution on #115.
