### ISSUE TITLE
Add scatterplot functionality

### ISSUE THREAD

**Issue by SamLau95** [dsten/datascience#94]
@a-adhikari need scatterplot functionality for lectures on two-variable things. My guess is that we'll just want to wrap `pyplot.scatter` (http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.scatter), similar to how we did it for `Table.barh`. I'm imagining the API to look something like:

```python
>>> t
x | y | z
1 | 4 | 10
3 | 2 | 2
3 | 3 | 2
9 | 1 | 1

>>> t.scatter('x')
<scatterplot with x as x-axis, y as y-axis>
<scatterplot with x as x-axis, z as y-axis>

>>> t.scatter('x', overlay=True)
<scatterplot with x as x-axis, y and z as y-axis values>
<scatterplot with x as x-axis, y and z as y-axis values>

>>> t.scatter('x', s = 10) # Passes vargs into pyplot.scatter
<scatterplot with x as x-axis, y as y-axis with marker size = 20>
<scatterplot with x as x-axis, z as y-axis with marker size = 20>
```

**Comment by SamLau95** [comment]
@taylorkmw , wanna take this on?

**Comment by deculler** [comment]
I put version in few days ago.  Called scatter.

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by SamLau95** [comment]
Oops! My bad.
