### ISSUE TITLE
Should rows and columns accept a label as index

### ISSUE THREAD

**Issue by deculler** [dsten/datascience#97]
The concept with rows what they provide an ordered set of elements in a row of a table, without losing the identity of the table.  They can function as a sequence, indexed by integer.  But they also hold on to the table and its labels that define its columns.  Thus, it would make sense to use the column label instead of the column index

```python
T = Table([[1,2,3],[4,5,6]],['one','two'])
T.rows[0]
>>> Row(one=1, two=4)
T.rows[0][0]
>>> 1
T.rows[0]['one']
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-d7994a039fcd> in <module>()
----> 1 T.rows[0]['one']

TypeError: tuple indices must be integers, not str
```

Instead you need the rather clumbsy

```python
T.rows[0][T.column_index('one')]
>>> 1
```

The same can be argued for T.columns('one').  Then there is no need to T.values('one').  Yes, both are equivalent to T['one'].

**Comment by mDibyo** [comment]
I feel this is closely tied to the resolution of #46 since we are discussing an alternate representation for a Row there.

**Comment by mDibyo** [comment]
In the current implementation, it is indeed possible to access row values with column labels, with `T.rows[0].one`. It does not work for column labels with spaces (basically all labels that are not valid variable names), so it would be good to have 'T.rows[0]['one']'.
Secondly, `T.values` returns an array of column values, but `T.columns` returns a table (a table view rather). So `T.columns` should still remain by its own.

**Comment by mDibyo** [comment]
Professor, just revisiting this. Was this resolved?

**Comment by papajohn** [comment]
Currently, a `Row` can get a value in a column using attribute (dot) syntax. I think this should change to a method, but at least it's possible, so closing this issue.
